sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jCBoG5uhP6JqV1BR1RfiavUS9CBNNMscRWwQC8AiCUKOCGtjRDpmn05/75D9E382Ao6j4K7j+DjPFtZX9DeGIKd8TxkMNLSJfmSEKWirWuCn7WmgLan0i9FLQ9VMgYatwrREjaScYmAVRSxsBi7XEOxJkgkN/FNRtP6BJtwWtG60NAEyU4DFUMhuCsUHwCzZU6KFKjkaf1eLV0Eg1QhEGHHNYem6I/R4zGsVYpk/WhYWF4JtWgmPEIMwixan1hja8IZHubUcoeN5aiRItInd2iprCyeyBrsavnmMmcqKD1DvYST5uXNbqekY6On3+dmE92B+DeCqxcvvedTfHjw5UzzLuR5wnf0d7GjjmN/inJRLZyqVLKqwYiF/qkyvixLPOdBFzom8Dx9UYEZ/7y+oxKjijArq6ex0sLPS87eXiqVS4xw9f/ZbJcCQHFmUX+RtcjG04eSa7+1MBCyPjdjLzcZUbyn5AgkR9IJDcntUi+k4qMbHrjVJWkuwsyxto3QiCLg72DP7mOEUIGncl38K0Eub84BbeyVu+Z0wl6geWREePmxdyr0KdzYnJY5Knd2aEOLl38rPFhsEYlzg4WdsWarLM6/yhI6xRStPIpq8jshsffTuuZCRiwkqVXn2qofddS3USmm2EBtjXq+DF5Wzd1RhCadQ0YaAt4ZXO1XUHo0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Old-French-Romances-Done-into-English_5988
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy